In [1]:
import pandas as pd 

In [190]:
data = pd.read_csv(r'C:\Users\Emma\Desktop\second_med_build\strain_data.csv')

In [158]:
data.tail()

Id       Strain    Race                      Flavors  \
2344  2344      Zeus Og  hybrid          Earthy, Woody, Pine   
2345  2345     Zkittlez  indica          Sweet, Berry, Grape   
2346  2346  Zombie Kush  indica  Earthy, Sweet, Spicy/Herbal   
2347  2347    Zombie Og  indica       Sweet, Earthy, Pungent   
2348  2348     Zoom Pie  indica       Berry, Earthy, Pungent   

                                              Positive  \
2344     Happy, Uplifted, Relaxed, Euphoric, Energetic   
2345        Relaxed, Euphoric, Happy, Uplifted, Sleepy   
2346       Relaxed, Sleepy, Talkative, Euphoric, Happy   
2347          Relaxed, Sleepy, Euphoric, Happy, Hungry   
2348  Relaxed, Hungry, Happy, Uplifted, Giggly, Sleepy   

                                 Negative  \
2344  Dizzy, Dry Mouth, Paranoid, Anxious   
2345  Dizzy, Dry Mouth, Paranoid, Anxious   
2346  Dizzy, Dry Mouth, Paranoid, Anxious   
2347  Dizzy, Dry Mouth, Paranoid, Anxious   
2348  Dizzy, Dry Mouth, Paranoid, Anxious   

                                                Medical  Rating  \
2344                        Depression, Stress, Fatigue     4.7   
2345  Depression, Insomnia, Pain, Stress, Nausea, Fa...     4.6   
2346                        Depression, Stress, Fatigue     5.0   
2347                        Depression, Stress, Fatigue     4.4   
2348  Insomnia, Pain, Cramps, Lack of Appetite, Stre...     4.6   

                                            Description  
2344  Zeus OG is a hybrid cross between Pineapple OG...  
2345  Zkittlez is an indica-dominant mix of Grape Ap...  
2346  Zombie Kush by Ripper Seeds comes from two dif...  
2347  If you’re looking to transform into a flesh-ea...  
2348  Zoom Pie (also known as Zombie Pie) is a heavy...

In [186]:
data.shape

(2349, 9)

In [187]:
(data.isnull() == True).sum()

Id              0
Strain          0
Race            0
Flavors        58
Positive       31
Negative        0
Medical         0
Rating          0
Description     0
dtype: int64

In [172]:
data.iloc[52]

Id                                                            52
Strain                                                 Afrikaner
Race                                                      sativa
Flavors                                                      NaN
Positive                                                     NaN
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical                              Depression, Stress, Fatigue
Rating                                                         0
Description    Afrikaner by Cannabaal and master grower Waldo...
everything                                                   NaN
Name: 52, dtype: object

In [191]:
#new csv has nans
import numpy as np

data = data.replace(np.nan, '')

In [184]:
#save a copy so DS all has the same thing

#data.to_csv(r'C:\Users\Emma\Desktop\second_med_build\DS_strain_data.csv') #ya only press this once

In [197]:
data['everything'] = data[['Flavors', 'Positive', 'Negative', 'Medical']].agg(','.join, axis= 1)

### Section

This section was an inital test of the data/nearest neighbors

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [199]:
vect = CountVectorizer()
vect.fit(data.everything)
dtm = vect.transform(data.everything)
dtm = pd.DataFrame(dtm.todense(), columns=vect.get_feature_names())

In [200]:
dtm

ammonia  anxious  appetite  apple  apricot  aroused  berry  blue  \
0           0        1         0      0        0        0      0     0   
1           0        1         0      0        0        0      0     0   
2           0        1         0      0        1        0      0     0   
3           0        1         0      0        0        0      0     0   
4           0        1         0      0        0        0      0     0   
...       ...      ...       ...    ...      ...      ...    ...   ...   
2344        0        1         0      0        0        0      0     0   
2345        0        1         0      0        0        0      1     0   
2346        0        1         0      0        0        0      0     0   
2347        0        1         0      0        0        0      0     0   
2348        0        1         1      0        0        0      1     0   

      blueberry  butter  ...  tar  tea  tingly  tobacco  tree  tropical  \
0             0       0  ...    0    0       1        0     0         0   
1             0       0  ...    0    0       0        0     0         0   
2             0       0  ...    0    0       1        0     0         0   
3             0       0  ...    0    0       0        0     0         0   
4             0       0  ...    0    0       0        0     0         0   
...         ...     ...  ...  ...  ...     ...      ...   ...       ...   
2344          0       0  ...    0    0       0        0     0         0   
2345          0       0  ...    0    0       0        0     0         0   
2346          0       0  ...    0    0       0        0     0         0   
2347          0       0  ...    0    0       0        0     0         0   
2348          0       0  ...    0    0       0        0     0         0   

      uplifted  vanilla  violet  woody  
0            0        0       0      0  
1            1        0       0      1  
2            1        0       0      0  
3            1        0       0      0  
4            0        0       0      0  
...        ...      ...     ...    ...  
2344         1        0       0      1  
2345         1        0       0      0  
2346         0        0       0      0  
2347         0        0       0      0  
2348         1        0       0      0  

[2349 rows x 88 columns]

In [201]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

tfidf = TfidfVectorizer(stop_words = 'english',
                      # ngram_range=(1,2),
                      # max_df=.5,
                      # min_df=3,
                       tokenizer= tokenize)

dtm = tfidf.fit_transform(data['everything'])
                       
dtm = pd.DataFrame(dtm.todense(), columns = tfidf.get_feature_names())
                       
dtm.head()

ammonia   anxious  appetite  apple   apricot  aroused  berry  blue  \
0      0.0  0.161923       0.0    0.0  0.000000      0.0    0.0   0.0   
1      0.0  0.115515       0.0    0.0  0.000000      0.0    0.0   0.0   
2      0.0  0.103597       0.0    0.0  0.614224      0.0    0.0   0.0   
3      0.0  0.143521       0.0    0.0  0.000000      0.0    0.0   0.0   
4      0.0  0.177011       0.0    0.0  0.000000      0.0    0.0   0.0   

   blueberry  butter  ...  tar  tea    tingly  tobacco  tree  tropical  \
0        0.0     0.0  ...  0.0  0.0  0.448640      0.0   0.0       0.0   
1        0.0     0.0  ...  0.0  0.0  0.000000      0.0   0.0       0.0   
2        0.0     0.0  ...  0.0  0.0  0.287038      0.0   0.0       0.0   
3        0.0     0.0  ...  0.0  0.0  0.000000      0.0   0.0       0.0   
4        0.0     0.0  ...  0.0  0.0  0.000000      0.0   0.0       0.0   

   uplifted  vanilla  violet     woody  
0  0.000000      0.0     0.0  0.000000  
1  0.156295      0.0     0.0  0.350248  
2  0.140171      0.0     0.0  0.000000  
3  0.194189      0.0     0.0  0.000000  
4  0.000000      0.0     0.0  0.000000  

[5 rows x 87 columns]

In [202]:
from sklearn.neighbors import NearestNeighbors

nn = NearestNeighbors(n_neighbors=5, algorithm='kd_tree')
nn.fit(dtm)

NearestNeighbors(algorithm='kd_tree', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [211]:
nn.kneighbors([dtm.iloc[492]])

(array([[0.        , 0.67578641, 0.67888603, 0.71395469, 0.73405097]]),
 array([[ 492, 1986, 1158, 1261, 1124]], dtype=int64))

In [204]:
data.iloc[0] # input value

Id                                                             0
Strain                                                    100 Og
Race                                                      hybrid
Flavors                                    Earthy, Sweet, Citrus
Positive          Creative, Energetic, Tingly, Euphoric, Relaxed
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical                              Depression, Stress, Fatigue
Rating                                                         4
Description    $100 OG is a 50/50 hybrid strain that packs a ...
everything     Earthy, Sweet, Citrus,Creative, Energetic, Tin...
Name: 0, dtype: object

In [205]:
data.iloc[574]

Id                                                           574
Strain                                        Confidential Wreck
Race                                                      hybrid
Flavors                                    Sweet, Citrus, Earthy
Positive             Hungry, Relaxed, Tingly, Uplifted, Creative
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical                              Depression, Stress, Fatigue
Rating                                                       4.2
Description    Confidential Wreck, also known as Lohan, is th...
everything     Sweet, Citrus, Earthy,Hungry, Relaxed, Tingly,...
Name: 574, dtype: object

In [206]:
data.iloc[2035]

Id                                                          2035
Strain                                           Sunset Sherbert
Race                                                      hybrid
Flavors                                    Sweet, Citrus, Earthy
Positive            Relaxed, Happy, Euphoric, Uplifted, Creative
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical                              Depression, Stress, Fatigue
Rating                                                       4.6
Description    Heir to the Girl Scout Cookies throne is Sunse...
everything     Sweet, Citrus, Earthy,Relaxed, Happy, Euphoric...
Name: 2035, dtype: object

In [208]:
data.iloc[22] #input value

Id                                                            22
Strain                                                  Aberdeen
Race                                                      hybrid
Flavors                          Menthol, Blue, Cheese, Chemical
Positive           Uplifted, Euphoric, Giggly, Energetic, Sleepy
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical                              Depression, Stress, Fatigue
Rating                                                       4.3
Description    Aberdeen is a variety of Agent Orange grown by...
everything     Menthol, Blue, Cheese, Chemical,Uplifted, Euph...
Name: 22, dtype: object

In [209]:
data.iloc[2043]

Id                                                          2043
Strain                                              Super Cheese
Race                                                      indica
Flavors                        Cheese, Blue Cheese, Earthy, Blue
Positive                        Relaxed, Euphoric, Happy, Sleepy
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical              Depression, Insomnia, Pain, Stress, Fatigue
Rating                                                       4.5
Description    Super Cheese, bred by Positronics, is a throwb...
everything     Cheese, Blue Cheese, Earthy, Blue,Relaxed, Eup...
Name: 2043, dtype: object

In [210]:
data.iloc[479]

Id                                                           479
Strain                                               Cheesewreck
Race                                                      hybrid
Flavors                      Cheese, Blue Cheese, Woody, Pungent
Positive       Relaxed, Happy, Creative, Uplifted, Giggly, Eu...
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical              Depression, Insomnia, Pain, Stress, Fatigue
Rating                                                       4.3
Description    Cheesewreck is a sativa-dominant hybrid bred b...
everything     Cheese, Blue Cheese, Woody, Pungent,Relaxed, H...
Name: 479, dtype: object

In [213]:
data.iloc[492] #input value

Id                                                           492
Strain                                                 Chemnesia
Race                                                      hybrid
Flavors                             Citrus, Diesel, Lemon, Sweet
Positive                     Relaxed, Euphoric, Happy, Energetic
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical             Depression, Pain, Fatigue, Headaches, Stress
Rating                                                       4.8
Description    Chemnesia has been dubbed one of the most powe...
everything     Citrus, Diesel, Lemon, Sweet,Relaxed, Euphoric...
Name: 492, dtype: object

In [214]:
data.iloc[1986]

Id                                                          1986
Strain                                                Star Tonic
Race                                                      hybrid
Flavors                             Citrus, Earthy, Sweet, Lemon
Positive       Relaxed, Euphoric, Happy, Creative, Focused, U...
Negative                            Dry Mouth, Paranoid, Anxious
Medical             Depression, Pain, Stress, Headaches, Fatigue
Rating                                                       4.7
Description    Star Tonic is a high-CBD strain bred from Deat...
everything     Citrus, Earthy, Sweet, Lemon,Relaxed, Euphoric...
Name: 1986, dtype: object

In [215]:
data.iloc[1158]

Id                                                          1158
Strain                                                  Kali Dog
Race                                                      hybrid
Flavors                            Citrus, Earthy, Lemon, Diesel
Positive       Relaxed, Happy, Energetic, Uplifted, Sleepy, F...
Negative                            Dry Mouth, Paranoid, Anxious
Medical        Pain, Stress, Lack of Appetite, Headaches, Fat...
Rating                                                       4.8
Description    This OG Kush and Sour Diesel hybrid from Royal...
everything     Citrus, Earthy, Lemon, Diesel,Relaxed, Happy, ...
Name: 1158, dtype: object

In [ ]:
#with samples being put in 

In [216]:
sample = ['sweet, citrus, pain']

In [217]:
new = tfidf.transform(sample)
nn.kneighbors(new.todense())

(array([[0.94952198, 0.96279755, 0.98896091, 0.99282592, 1.00196871]]),
 array([[1721,  727, 1614, 1364, 2299]], dtype=int64))

In [218]:
#with sample = ['sweet, citrus, pain']
#array([[1721,  727, 1614, 1364, 2299]], dtype=int64)

data.iloc[1721]

Id                                                          1721
Strain                                               Purple Thai
Race                                                      sativa
Flavors                                    Earthy, Citrus, Sweet
Positive       Relaxed, Euphoric, Happy, Creative, Uplifted, ...
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical                        Depression, Pain, Stress, Fatigue
Rating                                                       4.6
Description    Purple Thai is a mostly sativa strain that cro...
everything     Earthy, Citrus, Sweet,Relaxed, Euphoric, Happy...
Name: 1721, dtype: object

In [219]:
data.iloc[727]

Id                                                           727
Strain                                          Dutch Treat Haze
Race                                                      hybrid
Flavors                             Sweet, Earthy, Citrus, Berry
Positive           Relaxed, Euphoric, Happy, Energetic, Uplifted
Negative                            Dry Mouth, Paranoid, Anxious
Medical                        Depression, Pain, Stress, Fatigue
Rating                                                       4.5
Description    Two superstars from the Dutch cannabis scene m...
everything     Sweet, Earthy, Citrus, Berry,Relaxed, Euphoric...
Name: 727, dtype: object

In [220]:
data.iloc[1614]

Id                                                          1614
Strain                                             Pink Lemonade
Race                                                      hybrid
Flavors                                     Lemon, Citrus, Sweet
Positive            Relaxed, Happy, Energetic, Uplifted, Focused
Negative                            Dry Mouth, Paranoid, Anxious
Medical                        Depression, Pain, Stress, Fatigue
Rating                                                       4.5
Description    Pink Lemonade is a tart sativa-dominant hybrid...
everything     Lemon, Citrus, Sweet,Relaxed, Happy, Energetic...
Name: 1614, dtype: object

In [221]:
sample = ['headache, insomnia, pungent']

new = tfidf.transform(sample)
nn.kneighbors(new.todense())

(array([[0.88056576, 0.89043411, 0.90681119, 0.92817442, 0.93977065]]),
 array([[2338, 1482,  867,  968, 2264]], dtype=int64))

In [222]:
# with sample = ['headache, insomnia, pungent']
#array([[2338, 1482,  867,  968, 2264]], dtype=int64))

data.iloc[2338]

Id                                                          2338
Strain                                                  Yumboldt
Race                                                      indica
Flavors                                   Sweet, Pungent, Earthy
Positive       Relaxed, Euphoric, Happy, Uplifted, Sleepy, Hu...
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical        Depression, Insomnia, Pain, Stress, Headache, ...
Rating                                                       4.2
Description    Yumboldt can be hard to find but it is renowne...
everything     Sweet, Pungent, Earthy,Relaxed, Euphoric, Happ...
Name: 2338, dtype: object

In [223]:
data.iloc[1482]

Id                                                          1482
Strain                                                Obama Kush
Race                                                      indica
Flavors                             Sweet, Earthy, Pine, Pungent
Positive            Relaxed, Euphoric, Happy, Creative, Uplifted
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical        Depression, Insomnia, Pain, Stress, Headache, ...
Rating                                                       4.4
Description    This unique indica appropriately channels the ...
everything     Sweet, Earthy, Pine, Pungent,Relaxed, Euphoric...
Name: 1482, dtype: object

In [224]:
sample = ['uplifted, relaxed, cramps, nausea']

new = tfidf.transform(sample)
nn.kneighbors(new.todense())

(array([[0.78518469, 0.87915974, 0.89372137, 0.91921291, 0.94610798]]),
 array([[ 472, 1642,  252,  879, 1655]], dtype=int64))

In [225]:
# with sample = ['uplifted, realaxed, cramps, nausea']
#array([[ 472, 1642,  252,  879, 1655]], dtype=int64))

data.loc[472]

Id                                                           472
Strain                                            Champagne Kush
Race                                                      hybrid
Flavors                                   Earthy, Sweet, Pungent
Positive           Relaxed, Euphoric, Happy, Talkative, Uplifted
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical        Depression, Pain, Stress, Cramps, Nausea, Fatigue
Rating                                                       4.2
Description    Champagne Kush is an indica-dominant hybrid th...
everything     Earthy, Sweet, Pungent,Relaxed, Euphoric, Happ...
Name: 472, dtype: object

In [226]:
data.loc[1642]

Id                                                          1642
Strain                                             Predator Pink
Race                                                      hybrid
Flavors                           Earthy, Sweet, Berry, Tropical
Positive       Relaxed, Hungry, Euphoric, Happy, Tingly, Upli...
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical              Depression, Stress, Cramps, Nausea, Fatigue
Rating                                                       4.7
Description    A cross between Plushberry and Starfighter, Pr...
everything     Earthy, Sweet, Berry, Tropical,Relaxed, Hungry...
Name: 1642, dtype: object

In [227]:
data.loc[252]

Id                                                           252
Strain                                            Blackberry Pie
Race                                                      hybrid
Flavors                                  Sweet, Blueberry, Berry
Positive              Relaxed, Hungry, Euphoric, Happy, Creative
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical                    Pain, Cramps, Nausea, Stress, Fatigue
Rating                                                       4.7
Description    Blackberry Pie is a hybrid cross of Jojorizo’s...
everything     Sweet, Blueberry, Berry,Relaxed, Hungry, Eupho...
Name: 252, dtype: object

In [228]:
data.loc[879]

Id                                                           879
Strain                                               Goji Diesel
Race                                                      hybrid
Flavors                                                         
Positive       Relaxed, Euphoric, Creative, Uplifted, Focused...
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical                      Depression, Stress, Cramps, Fatigue
Rating                                                       4.8
Description    Goji Diesel is an uplifting strain brought to ...
everything     ,Relaxed, Euphoric, Creative, Uplifted, Focuse...
Name: 879, dtype: object

### Section

This section is a test to see if the model performs well only testing on medical data. Tyler and I talked earlier about having two models, or a model and a filter, with the first model only suggesting relief for medical symptoms, and making all the other inputs secondary to it. So, have this medical model put out, say fifty suggestions and put those in a model or through a filter to narrow it down given flavor, race, etc.

In [237]:
########################### just medical 

vect = CountVectorizer()
vect.fit(data.Medical)
dtm = vect.transform(data.Medical)
dtmM = pd.DataFrame(dtm.todense(), columns=vect.get_feature_names())

In [239]:
tfidf = TfidfVectorizer(stop_words = 'english',
                      # ngram_range=(1,2),
                      # max_df=.5,
                      # min_df=3,
                       tokenizer= tokenize)

dtmM = tfidf.fit_transform(data['Medical'])
                       
dtmM = pd.DataFrame(dtmM.todense(), columns = tfidf.get_feature_names())
                       
dtmM.head()

appetite  cramps  depression  eye   fatigue  headache  headaches  \
0       0.0     0.0    0.618926  0.0  0.555397       0.0        0.0   
1       0.0     0.0    0.618926  0.0  0.555397       0.0        0.0   
2       0.0     0.0    0.618926  0.0  0.555397       0.0        0.0   
3       0.0     0.0    0.618926  0.0  0.555397       0.0        0.0   
4       0.0     0.0    0.618926  0.0  0.555397       0.0        0.0   

   inflammation  insomnia  lack  nausea  pain  pressure  seizures  spasticity  \
0           0.0       0.0   0.0     0.0   0.0       0.0       0.0         0.0   
1           0.0       0.0   0.0     0.0   0.0       0.0       0.0         0.0   
2           0.0       0.0   0.0     0.0   0.0       0.0       0.0         0.0   
3           0.0       0.0   0.0     0.0   0.0       0.0       0.0         0.0   
4           0.0       0.0   0.0     0.0   0.0       0.0       0.0         0.0   

     stress  
0  0.555397  
1  0.555397  
2  0.555397  
3  0.555397  
4  0.555397

In [240]:
from sklearn.neighbors import NearestNeighbors

nn = NearestNeighbors(n_neighbors=5, algorithm='kd_tree')
nn.fit(dtmM)

NearestNeighbors(algorithm='kd_tree', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [241]:
nn.kneighbors([dtmM.iloc[0]])

(array([[0., 0., 0., 0., 0.]]),
 array([[ 157,    0,  610,   67, 1172]], dtype=int64))

In [242]:
data['Medical'].iloc[0] #input variable 

'Depression, Stress, Fatigue'

In [245]:
data.iloc[157]

Id                                                           157
Strain                                           Banana Cream Og
Race                                                      hybrid
Flavors                                        Minty, Mint, Pine
Positive            Relaxed, Creative, Tingly, Uplifted, Focused
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical                              Depression, Stress, Fatigue
Rating                                                       4.8
Description    Banana Cream OG is grown by Vagrant Hill Farms...
everything     Minty, Mint, Pine,Relaxed, Creative, Tingly, U...
tokens         [minty, mint, pine, relaxed, creative, tingly,...
Name: 157, dtype: object

In [246]:
data.iloc[610]

Id                                                           610
Strain                                            Critical Skunk
Race                                                      hybrid
Flavors                                            Earthy, Skunk
Positive               Happy, Relaxed, Creative, Hungry, Aroused
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical                              Depression, Stress, Fatigue
Rating                                                       4.5
Description    Critical Skunk is a hybrid bred by Mr. Nice Se...
everything     Earthy, Skunk,Happy, Relaxed, Creative, Hungry...
tokens         [earthy, skunk, happy, relaxed, creative, hung...
Name: 610, dtype: object

In [248]:
data.iloc[16]

Id                                                          1642
Strain                                             Predator Pink
Race                                                      hybrid
Flavors                           Earthy, Sweet, Berry, Tropical
Positive       Relaxed, Hungry, Euphoric, Happy, Tingly, Upli...
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical              Depression, Stress, Cramps, Nausea, Fatigue
Rating                                                       4.7
Description    A cross between Plushberry and Starfighter, Pr...
everything     Earthy, Sweet, Berry, Tropical,Relaxed, Hungry...
tokens         [earthy, sweet, berry, tropical, relaxed, hung...
Name: 1642, dtype: object

In [249]:
data.iloc[1171]

Id                                                          1171
Strain                                              Kerala Krush
Race                                                      sativa
Flavors                                     Mango, Sweet, Orange
Positive              Relaxed, Hungry, Happy, Energetic, Focused
Negative                     Dizzy, Dry Mouth, Paranoid, Anxious
Medical              Depression, Cramps, Nausea, Stress, Fatigue
Rating                                                       4.6
Description    Kerala Krush by Flying Dutchmen is an 85% sati...
everything     Mango, Sweet, Orange,Relaxed, Hungry, Happy, E...
tokens         [mango, sweet, orange, relaxed, hungry, happy,...
Name: 1171, dtype: object

In [250]:
user_test = pd.read_csv(r'C:\Users\Emma\Desktop\second_med_build\random_users.csv')

In [251]:
user_test.head()

User_Id            Race                                            Flavors  \
0        0  sativa, hybrid  Chestnut, Lavender, Tropical, Berry, Butter, F...   
1        1  indica, sativa  Strawberry, Pungent, Orange, Lime, Lemon, Lave...   
2        2          sativa  Tropical, Grapefruit, Lemon, Minty, Apple, Tre...   
3        3          indica  Nutty, Lime, Plum, Berry, Vanilla, Coffee, Pep...   
4        4          hybrid  Apple, Menthol, Spicy/Herbal, Cheese, Fruit, B...   

                                            Positive  \
0                                                NaN   
1  Focused, Tingly, Uplifted, Euphoric, Giggly, S...   
2      Talkative, Focused, Euphoric, Relaxed, Hungry   
3                                   Uplifted, Hungry   
4                                Uplifted, Energetic   

                                 Negative  \
0              Dry Mouth, Paranoid, Dizzy   
1                                 Anxious   
2                                   Dizzy   
3  Dry Mouth, Dry Eyes, Anxious, Paranoid   
4             Dry Eyes, Anxious, Paranoid   

                                             Medical  
0    Insomnia, Headaches, Cramps, Seizures, Headache  
1                                   Lack of Appetite  
2  Lack of Appetite, Inflammation, Cramps, Muscle...  
3                                             Nausea  
4  Headaches, Eye Pressure, Fatigue, Spasticity, ...

In [252]:
user_test = user_test.replace(np.nan, '')

In [255]:
user_test['everything'] = user_test[['Race', 'Flavors', 'Positive', 'Negative', 'Medical']].agg(','.join, axis= 1)

In [260]:
sample

'sativa, hybrid,Chestnut, Lavender, Tropical, Berry, Butter, Fruit, Coffee, Plum,,Dry Mouth, Paranoid, Dizzy,Insomnia, Headaches, Cramps, Seizures, Headache'

In [269]:
sample = [user_test['Medical'][0]]

new = tfidf.transform(sample)
nn.kneighbors(new.todense())

(array([[0.71301946, 0.80116447, 0.80116447, 0.90036502, 0.95390157]]),
 array([[ 929, 1366,  246, 1720,   69]], dtype=int64))

In [266]:
print(sample,data.iloc[929],data.iloc[1366])

['Insomnia, Headaches, Cramps, Seizures, Headache'] Id                                                           929
Strain                                           Grapefruit Kush
Race                                                      hybrid
Flavors                        Grapefruit, Earthy, Citrus, Sweet
Positive       Relaxed, Hungry, Euphoric, Happy, Uplifted, Fo...
Negative           Dizzy, Dry Mouth, Paranoid, Dry Eyes, Anxious
Medical                      Insomnia, Stress, Fatigue, Seizures
Rating                                                       4.3
Description    This cannabis strain is a cross of BC Kush and...
everything     Grapefruit, Earthy, Citrus, Sweet,Relaxed, Hun...
tokens         [grapefruit, earthy, citrus, sweet, relaxed, h...
Name: 929, dtype: object Id                                                          1366
Strain                                                Maui Haole
Race                                                      hybrid
Flavors      

In [276]:
count = []

for row in user_test['Medical'][:50]:
    sample = [row]
    new = tfidf.transform(sample)
    neighbors = nn.kneighbors(new.todense())
    neighbors = neighbors[1]
    count.append(neighbors)
    for i in neighbors:
        print('This is the sample:', sample)
        print(data['Medical'].iloc[i])
        print('\n')

This is the sample: ['Insomnia, Headaches, Cramps, Seizures, Headache']
929                   Insomnia, Stress, Fatigue, Seizures
1366          Depression, Pain, Stress, Seizures, Fatigue
246           Depression, Pain, Seizures, Stress, Fatigue
1720    Depression, Insomnia, Cramps, Headaches, Stres...
69         Depression, Cramps, Fatigue, Headaches, Stress
Name: Medical, dtype: object


This is the sample: ['Lack of Appetite']
1184                Stress, Lack of Appetite, Fatigue
1311    Depression, Stress, Lack of Appetite, Fatigue
1206    Depression, Stress, Lack of Appetite, Fatigue
1537    Depression, Stress, Lack of Appetite, Fatigue
1379    Depression, Stress, Lack of Appetite, Fatigue
Name: Medical, dtype: object


This is the sample: ['Lack of Appetite, Inflammation, Cramps, Muscle Spasms, Headache, Insomnia']
2223    Pain, Cramps, Lack of Appetite, Inflammation, ...
118     Pain, Cramps, Lack of Appetite, Inflammation, ...
1781    Depression, Insomnia, Cramps, Inflammation,

In [277]:
count #I am about to cycle through this and count how many duplicates there are to measure if this model is sound

[array([[ 929, 1366,  246, 1720,   69]], dtype=int64),
 array([[1184, 1311, 1206, 1537, 1379]], dtype=int64),
 array([[2223,  118, 1781, 1257, 1097]], dtype=int64),
 array([[ 732,  206, 1032, 1041,  270]], dtype=int64),
 array([[1416,  400, 1607, 1600, 1529]], dtype=int64),
 array([[ 356,  756, 2099, 1838, 2160]], dtype=int64),
 array([[ 732,  206, 1032, 1041,  270]], dtype=int64),
 array([[ 246, 1366,  179,  929,  705]], dtype=int64),
 array([[1425, 1393,  300,  587,  990]], dtype=int64),
 array([[1838, 2099,  356,  756, 1802]], dtype=int64),
 array([[ 756,  356, 1838, 2099, 1802]], dtype=int64),
 array([[ 587, 2257, 1393,  300,  715]], dtype=int64),
 array([[ 179,  929,   78,  246, 1366]], dtype=int64),
 array([[1825,  751, 1298, 2282, 1716]], dtype=int64),
 array([[2190,  751, 2248, 1198, 1298]], dtype=int64),
 array([[2052, 1156,   65, 2084, 1556]], dtype=int64),
 array([[1666, 1825,  400,  751, 1416]], dtype=int64),
 array([[1840,  990, 1425,  587, 1393]], dtype=int64),
 array([[1

### Section 

this is the topic modeling to replicate clustering but with more interpretability

In [ ]:
##########topic modeling

In [229]:
from gensim.utils import simple_preprocess

def tokenize(text):
    return [token for token in simple_preprocess(text)]

In [230]:
data['tokens'] = data['everything'].apply(tokenize)

In [231]:
from gensim import corpora

id2word = corpora.Dictionary(data['tokens'])

In [232]:
id2word[30]

'flowery'

In [233]:
#create corpus for lda 

corpus = [id2word.doc2bow(text) for text in data['tokens']]

In [234]:
from gensim.models.ldamulticore import LdaMulticore

lda = LdaMulticore(corpus=corpus, #we gotta give them the bag of words
                  id2word=id2word, #we wanna see the words
                  random_state=42, 
                  num_topics = 5, #just gonna try ten, probably not a huge variety of reviews
                  passes= 25, #he said to amp it up to 100, but imma start small
                  workers=8)

In [235]:
lda.print_topics()

[(0,
  '0.069*"dry" + 0.050*"pain" + 0.049*"relaxed" + 0.048*"paranoid" + 0.048*"anxious" + 0.048*"stress" + 0.048*"mouth" + 0.048*"fatigue" + 0.047*"happy" + 0.045*"euphoric"'),
 (1,
  '0.055*"spicy" + 0.055*"herbal" + 0.054*"dry" + 0.052*"paranoid" + 0.052*"stress" + 0.052*"fatigue" + 0.052*"anxious" + 0.052*"mouth" + 0.044*"depression" + 0.039*"happy"'),
 (2,
  '0.062*"mouth" + 0.062*"fatigue" + 0.062*"anxious" + 0.062*"stress" + 0.062*"paranoid" + 0.061*"dry" + 0.059*"depression" + 0.056*"relaxed" + 0.054*"dizzy" + 0.047*"happy"'),
 (3,
  '0.091*"lack" + 0.091*"appetite" + 0.091*"of" + 0.049*"dry" + 0.038*"happy" + 0.038*"pain" + 0.036*"fatigue" + 0.036*"mouth" + 0.036*"stress" + 0.036*"paranoid"'),
 (4,
  '0.064*"dry" + 0.057*"mouth" + 0.057*"fatigue" + 0.057*"stress" + 0.057*"anxious" + 0.057*"paranoid" + 0.055*"depression" + 0.049*"uplifted" + 0.048*"happy" + 0.046*"dizzy"')]

In [236]:
import gensim
import pyLDAvis.gensim

pyLDAvis.enable_notebook()

pyLDAvis.gensim.prepare(lda, corpus, id2word)

C:\ProgramData\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:257: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  return pd.concat([default_term_info] + list(topic_dfs))


PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
4      0.009170 -0.022902       1        1  31.601042
2      0.033699  0.049807       2        1  25.630939
0      0.014464  0.053251       3        1  20.741297
3     -0.125992 -0.016773       4        1  11.046263
1      0.068659 -0.063384       5        1  10.980463, topic_info=   Category        Freq       Term        Total  loglift  logprob
56  Default  444.000000       lack   444.000000  30.0000  30.0000
55  Default  444.000000   appetite   444.000000  29.0000  29.0000
58  Default  444.000000         of   444.000000  28.0000  28.0000
19  Default  265.000000      spicy   265.000000  27.0000  27.0000
17  Default  265.000000     herbal   265.000000  26.0000  26.0000
..      ...         ...        ...          ...      ...      ...
6    Topic5  114.507591     earthy  1317.355469  -0.2337  -3.7389
54   Topic5  104.948013       pain  1152.872314  -0.1875  -3.8261
7    Topic5   76.206238  energetic   787.466309  -0.1263  -4.1461
14   Topic5   84.159119      sweet  1179.153809  -0.4308  -4.0468
28   Topic5   49.899246     sleepy   841.663025  -0.6163  -4.5695

[250 rows x 6 columns], token_table=      Topic      Freq     Term
term                          
37        1  0.048466  ammonia
37        2  0.024233  ammonia
37        3  0.024233  ammonia
37        5  0.920846  ammonia
0         1  0.337206  anxious
...     ...       ...      ...
21        1  0.169254    woody
21        2  0.624939    woody
21        3  0.006510    woody
21        4  0.087882    woody
21        5  0.107411    woody

[305 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[5, 3, 1, 4, 2])

In [99]:
data['everything'][0]

"['Earthy', 'Chemical', 'Pine', 'Spicy/Herbal'],['Relaxed', 'Hungry', 'Happy', 'Sleepy', 'Creative', 'Focused'],['Dizzy'],['Depression', 'Insomnia', 'Pain', 'Stress', 'Lack of Appetite']"

In [102]:
for row in data['everything']:
    #row = tuple(row)
    for l1, l2, l3, l4 in row:
        altogether= [*l1, *l2, *l3, *l4]
        row = altogether

ValueError: not enough values to unpack (expected 4, got 1)

In [109]:
#clustering 

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3).fit(data['tokens'])
centroids = kmeans.cluster_centers_
print(centroids)

#plt.scatter(df['x'], df['y'], c= kmeans.labels_.astype(float), s=50, alpha=0.5)
#plt.scatter(centroids[:, 0], centroids[:, 1], c='red', s=50)

ValueError: setting an array element with a sequence.

In [ ]:
###########################