In [1]:
import pandas as pd
import numpy as np

import spacy
from spacy.tokenizer import Tokenizer

from sklearn.externals import joblib 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

nlp = spacy.load("en_core_web_lg")

In [25]:
data1 = pd.read_csv('../merged.csv', na_values='None')
# data = data.set_index('name')
print(data.shape)
data1.head()

(2349, 11)


id               name    race  \
0   1              Afpak  hybrid   
1   2            African  sativa   
2   3  Afternoon Delight  hybrid   
3   4            Afwreck  hybrid   
4   5       Agent Orange  hybrid   

                                             flavors  \
0     ['Earthy', 'Chemical', 'Pine', 'Spicy/Herbal']   
1    ['Spicy/Herbal', 'Pungent', 'Earthy', 'Pepper']   
2  ['Pepper', 'Flowery', 'Pine', 'Pungent', 'Citr...   
3           ['Pine', 'Earthy', 'Flowery', 'Pungent']   
4            ['Citrus', 'Orange', 'Sweet', 'Earthy']   

                                            positive  \
0  ['Relaxed', 'Hungry', 'Happy', 'Sleepy', 'Crea...   
1  ['Euphoric', 'Happy', 'Creative', 'Energetic',...   
2  ['Relaxed', 'Hungry', 'Euphoric', 'Uplifted', ...   
3  ['Relaxed', 'Happy', 'Creative', 'Uplifted', '...   
4  ['Relaxed', 'Euphoric', 'Happy', 'Energetic', ...   

                                         negative  \
0                                       ['Dizzy']   
1                                   ['Dry Mouth']   
2              ['Dizzy', 'Dry Mouth', 'Paranoid']   
3  ['Dizzy', 'Dry Mouth', 'Paranoid', 'Dry Eyes']   
4  ['Dizzy', 'Dry Mouth', 'Paranoid', 'Dry Eyes']   

                                             medical  Rating  \
0  ['Depression', 'Insomnia', 'Pain', 'Stress', '...     4.2   
1  ['Depression', 'Pain', 'Stress', 'Lack of Appe...     3.9   
2  ['Depression', 'Insomnia', 'Pain', 'Stress', '...     4.8   
3  ['Pain', 'Stress', 'Headache', 'Fatigue', 'Hea...     4.2   
4  ['Depression', 'Pain', 'Stress', 'Nausea', 'He...     4.2   

                                         Description  
0  Afpak, named for its direct Afghani and Pakist...  
1  African refers to the indigenous varieties of ...  
2  Afternoon Delight, created by Colorado Seed In...  
3  Afwreck is a hybrid cross of Afghani and Train...  
4  Don’t let the name scare you! The only herbici...

In [33]:
data1.medical.str.contains("['Depression', 'Stress', 'Fatigue']").sum()

1916

In [35]:
data.Medical.str.contains("Depression, Stress, Fatigue").sum()

931

In [17]:
data = pd.read_csv('../DS_strain_data.csv', na_values='None')
# data = data.set_index('name')
print(data.shape)
data.head()

(2349, 11)


Unnamed: 0  Id      Strain    Race                      Flavors  \
0           0   0      100 Og  hybrid        Earthy, Sweet, Citrus   
1           1   1        1024  sativa    Spicy/Herbal, Sage, Woody   
2           2   2    13 Dawgs  hybrid  Apricot, Citrus, Grapefruit   
3           3   3    24K Gold  hybrid       Citrus, Earthy, Orange   
4           4   4  3 Bears Og  indica       Sweet, Pungent, Earthy   

                                         Positive  \
0  Creative, Energetic, Tingly, Euphoric, Relaxed   
1   Uplifted, Happy, Relaxed, Energetic, Creative   
2     Tingly, Creative, Hungry, Relaxed, Uplifted   
3   Happy, Relaxed, Euphoric, Uplifted, Talkative   
4      Relaxed, Happy, Sleepy, Creative, Euphoric   

                              Negative                      Medical  Rating  \
0  Dizzy, Dry Mouth, Paranoid, Anxious  Depression, Stress, Fatigue     4.0   
1  Dizzy, Dry Mouth, Paranoid, Anxious  Depression, Stress, Fatigue     4.4   
2  Dizzy, Dry Mouth, Paranoid, Anxious  Depression, Stress, Fatigue     4.2   
3  Dizzy, Dry Mouth, Paranoid, Anxious  Depression, Stress, Fatigue     4.6   
4  Dizzy, Dry Mouth, Paranoid, Anxious  Depression, Stress, Fatigue     4.4   

                                         Description  \
0  $100 OG is a 50/50 hybrid strain that packs a ...   
1  1024 is a sativa-dominant hybrid bred in Spain...   
2  13 Dawgs is a hybrid of G13 and Chemdawg genet...   
3  Also known as Kosher Tangie, 24k Gold is a 60%...   
4  3 Bears OG by Mephisto Genetics is an autoflow...   

                                          everything  
0  Earthy, Sweet, Citrus,Creative, Energetic, Tin...  
1  Spicy/Herbal, Sage, Woody,Uplifted, Happy, Rel...  
2  Apricot, Citrus, Grapefruit,Tingly, Creative, ...  
3  Citrus, Earthy, Orange,Happy, Relaxed, Euphori...  
4  Sweet, Pungent, Earthy,Relaxed, Happy, Sleepy,...

In [18]:
data.isnull().sum()

Unnamed: 0      0
Id              0
Strain          0
Race            0
Flavors        58
Positive       31
Negative        0
Medical         0
Rating          0
Description     5
everything      0
dtype: int64

In [19]:
tokenizer = Tokenizer(nlp.vocab)

In [20]:
def tokenize(document):
    
    doc = nlp(document)
    
    return [token.lemma_.strip() for token in doc if (token.is_stop != True) and (token.is_punct != True)]

In [24]:
data.head(100)

Unnamed: 0  Id                  Strain    Race  \
0            0   0                  100 Og  hybrid   
1            1   1                    1024  sativa   
2            2   2                13 Dawgs  hybrid   
3            3   3                24K Gold  hybrid   
4            4   4              3 Bears Og  indica   
5            5   5                 3 Kings  hybrid   
6            6   6                  303 Og  indica   
7            7   7                  3D Cbd  sativa   
8            8   8  3Rd Coast Panama Chunk  hybrid   
9            9   9                3X Crazy  indica   
10          10  10                501St Og  hybrid   
11          11  11             5Th Element  indica   
12          12  12            707 Headband  hybrid   
13          13  13             8 Ball Kush  indica   
14          14  14                  818 Og  indica   
15          15  15                  831 Og  indica   
16          16  16          9 Pound Hammer  indica   
17          17  17                91 Krypt  indica   
18          18  18          98 White Widow  hybrid   
19          19  19                    A 10  indica   
20          20  20                   A Dub  hybrid   
21          21  21                 A Train  hybrid   
22          22  22                Aberdeen  hybrid   
23          23  23              Abusive Og  indica   
24          24  24           Acapulco Gold  sativa   
25          25  25                    Acdc  hybrid   
26          26  26           Ace Killer Og  indica   
27          27  27           Ace Of Spades  indica   
28          28  28                    Aceh  sativa   
29          29  29                    Acid  hybrid   
..         ...  ..                     ...     ...   
70          70  70            Alien Asshat  hybrid   
71          71  71             Alien Bubba  indica   
72          72  72              Alien Dawg  indica   
73          73  73          Alien Dutchess  sativa   
74          74  74     Alien Hallucination  hybrid   
75          75  75           Alien Inferno  hybrid   
76          76  76              Alien Kush  indica   
77          77  77                Alien Og  hybrid   
78          78  78           Alien Reunion  hybrid   
79          79  79              Alien Rift  indica   
80          80  80        Alien Rock Candy  hybrid   
81          81  81        Alien Sour Apple  hybrid   
82          82  82          Alien Stardawg  sativa   
83          83  83        Alien Technology  indica   
84          84  84     Aliens On Moonshine  indica   
85          85  85        Allen Iverson Og  indica   
86          86  86            Allen Wrench  sativa   
87          87  87                 Allkush  indica   
88          88  88                   Aloha  sativa   
89          89  89     Aloha Grape Stomper  hybrid   
90          90  90            Aloha Limone  hybrid   
91          91  91              Alohaberry  hybrid   
92          92  92              Alpha Blue  sativa   
93          93  93               Alpha Cow  sativa   
94          94  94           Alpha Express  sativa   
95          95  95                Alpha Og  hybrid   
96          96  96             Alpine Blue  hybrid   
97          97  97             Alpine Star  indica   
98          98  98               Als Dream  hybrid   
99          99  99                Ambrosia  hybrid   

                                              Flavors  \
0                               Earthy, Sweet, Citrus   
1                           Spicy/Herbal, Sage, Woody   
2                         Apricot, Citrus, Grapefruit   
3                              Citrus, Earthy, Orange   
4                              Sweet, Pungent, Earthy   
5                              Earthy, Sweet, Pungent   
6                             Citrus, Pungent, Earthy   
7                              Earthy, Woody, Flowery   
8                                        Pine, Diesel   
9                                Earthy, Grape, Sweet   
10                          

In [22]:
tfidf = TfidfVectorizer(stop_words = 'english',
                      # ngram_range=(1,2),
                      # max_df=.5,
                      # min_df=3,
                       tokenizer= tokenize)

dtm = tfidf.fit_transform(data['everything'])

dtm = pd.DataFrame(dtm.todense(), columns = tfidf.get_feature_names())
dtm.head()

ammonia   anxious  appetite  apple   apricot  arouse  aroused  berry  \
0      0.0  0.161836       0.0    0.0  0.000000     0.0      0.0    0.0   
1      0.0  0.115481       0.0    0.0  0.000000     0.0      0.0    0.0   
2      0.0  0.103582       0.0    0.0  0.614133     0.0      0.0    0.0   
3      0.0  0.143473       0.0    0.0  0.000000     0.0      0.0    0.0   
4      0.0  0.176918       0.0    0.0  0.000000     0.0      0.0    0.0   

   berry,,dizzy  blue  ...  tar  tea    tingly  tobacco  tree  tropical  \
0           0.0   0.0  ...  0.0  0.0  0.448400      0.0   0.0       0.0   
1           0.0   0.0  ...  0.0  0.0  0.000000      0.0   0.0       0.0   
2           0.0   0.0  ...  0.0  0.0  0.286995      0.0   0.0       0.0   
3           0.0   0.0  ...  0.0  0.0  0.000000      0.0   0.0       0.0   
4           0.0   0.0  ...  0.0  0.0  0.000000      0.0   0.0       0.0   

   uplifted  vanilla  violet     woody  
0  0.000000      0.0     0.0  0.000000  
1  0.156250      0.0     0.0  0.350146  
2  0.140150      0.0     0.0  0.000000  
3  0.194124      0.0     0.0  0.000000  
4  0.000000      0.0     0.0  0.000000  

[5 rows x 96 columns]

In [36]:
# Fit on DTM
nn = NearestNeighbors(n_neighbors=5, algorithm='ball_tree')
nn.fit(dtm)

NearestNeighbors(algorithm='ball_tree', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=None, n_neighbors=5, p=2, radius=1.0)

In [37]:
data.iloc[552]

Unnamed: 0                                                   552
Id                                                           552
Strain                                                    Citrix
Race                                                      hybrid
Flavors                        Citrus, Grapefruit, Orange, Lemon
Positive       Euphoric, Happy, Energetic, Uplifted, Aroused,...
Negative                            Dry Mouth, Paranoid, Anxious
Medical        Depression, Stress, Lack of Appetite, Nausea, ...
Rating                                                       4.3
Description    Citrix is a hybrid cannabis strain that draws ...
everything     Citrus, Grapefruit, Orange, Lemon,Euphoric, Ha...
Name: 552, dtype: object

In [38]:
nn.kneighbors([dtm.iloc[100]])  # The second set of values are the suggested strains.

(array([[0.        , 0.55213002, 0.66428793, 0.67274962, 0.67450085]]),
 array([[ 100, 1677, 1752,  506, 1412]]))

In [39]:
test_phrase = ["""
I want something earthy Euphoric dizzy Depression
"""]

In [40]:
new = tfidf.transform(test_phrase)

In [41]:
nn.kneighbors(new.todense())  # The second set of values are the suggested strains.

(array([[0.92677693, 0.98572156, 0.99225521, 1.00824068, 1.00956997]]),
 array([[ 530,  138, 2271,  167, 1857]]))

In [42]:
from sklearn.externals import joblib 
joblib.dump(tfidf, 'baseline_tfidf.pkl')

['baseline_tfidf.pkl']

In [43]:
joblib.dump(nn, 'baseline_model.pkl')

['baseline_model.pkl']

In [44]:
data.head()

Unnamed: 0  Id      Strain    Race                      Flavors  \
0           0   0      100 Og  hybrid        Earthy, Sweet, Citrus   
1           1   1        1024  sativa    Spicy/Herbal, Sage, Woody   
2           2   2    13 Dawgs  hybrid  Apricot, Citrus, Grapefruit   
3           3   3    24K Gold  hybrid       Citrus, Earthy, Orange   
4           4   4  3 Bears Og  indica       Sweet, Pungent, Earthy   

                                         Positive  \
0  Creative, Energetic, Tingly, Euphoric, Relaxed   
1   Uplifted, Happy, Relaxed, Energetic, Creative   
2     Tingly, Creative, Hungry, Relaxed, Uplifted   
3   Happy, Relaxed, Euphoric, Uplifted, Talkative   
4      Relaxed, Happy, Sleepy, Creative, Euphoric   

                              Negative                      Medical  Rating  \
0  Dizzy, Dry Mouth, Paranoid, Anxious  Depression, Stress, Fatigue     4.0   
1  Dizzy, Dry Mouth, Paranoid, Anxious  Depression, Stress, Fatigue     4.4   
2  Dizzy, Dry Mouth, Paranoid, Anxious  Depression, Stress, Fatigue     4.2   
3  Dizzy, Dry Mouth, Paranoid, Anxious  Depression, Stress, Fatigue     4.6   
4  Dizzy, Dry Mouth, Paranoid, Anxious  Depression, Stress, Fatigue     4.4   

                                         Description  \
0  $100 OG is a 50/50 hybrid strain that packs a ...   
1  1024 is a sativa-dominant hybrid bred in Spain...   
2  13 Dawgs is a hybrid of G13 and Chemdawg genet...   
3  Also known as Kosher Tangie, 24k Gold is a 60%...   
4  3 Bears OG by Mephisto Genetics is an autoflow...   

                                          everything  
0  Earthy, Sweet, Citrus,Creative, Energetic, Tin...  
1  Spicy/Herbal, Sage, Woody,Uplifted, Happy, Rel...  
2  Apricot, Citrus, Grapefruit,Tingly, Creative, ...  
3  Citrus, Earthy, Orange,Happy, Relaxed, Euphori...  
4  Sweet, Pungent, Earthy,Relaxed, Happy, Sleepy,...

In [45]:
class strainSuggester():
    """
    Generates 5 suggested strains based on input text
    """
    def __init__(self):
        self.tfidf = joblib.load('baseline_tfidf.pkl')
        self.test_model = joblib.load('baseline_model.pkl')
    
    def suggestStrain(self, input, neighbors=5):
        vectorized = (tfidf.transform(input)).todense()
        results = nn.kneighbors(vectorized, neighbors)
        return results[0]

In [25]:
ss = strainSuggester()
ss.suggestStrain(test_phrase)

array([[1.04117704, 1.04117704, 1.04117704, 1.04117704, 1.04117704]])